version: "3"
services:
  web:
    container_name: phpserver
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysqlserver
    volumes:
      - ./${CONFIG_DIR}/apache/apache2.conf:/etc/apache2/apache2.conf
      - ./${CONFIG_DIR}/php/php.ini:/etc/php/${PHP_VERSION}/apache2/php.ini
      - ./${CONFIG_DIR}/apache/sites-available:/etc/apache2/sites-available
      - ${SRC_DIR}:/var/www/html/
      - ./${CONFIG_DIR}/php/xdebug.ini:/etc/php/${PHP_VERSION}/mods-available/xdebug.ini
      - ./logs:/var/www/logs
    links:
      - mysqlserver
    restart: on-failure
    networks:
      local_net:
        ipv4_address: 172.28.1.1

  mysqlserver: 
    container_name: mysqlserver
    env_file: .env
    image: mysql:5.5
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_HOST: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/logs:/var/log
      - ./database/my.cnf:/etc/mysql/my.cnf
    restart: on-failure
    networks:
      local_net:
        ipv4_address: 172.28.1.2

networks:
  local_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/16